export {default as Navbar} from './navbar/navbar';
export {default as Footer} from './footer/footer';
export {default as HomePage} from './home-page/home-page';
export {default as About} from './about/about';
export {default as Contact} from './contact/contact';
export {default as Login} from './login/login';
export {default as SignUp} from './sign-up/signup';
export {default as Blog} from './blog/blog';
export {default as SimpleSlider} from './slider/slider'
export {default as Products} from './products/products'